apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  storageClassName: local-storage
  volumeName: nginx-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
